"""Deterministic assembly of a unifying ``main.ptx`` project manifest.

The pipeline emits one ``.ptx`` per chapter (and per front/back-matter file),
each a standalone fragment rooted at ``<section>`` — that is what
pandoc/``pretext.lua`` produces, deliberately (see ``convert/pandoc.py``).
Nothing ties them together, so the output directory is a pile of fragments
rather than a project the PreTeXt-CLI can build.

This module is that missing piece: it collects the fragments under a single
``<pretext>`` root, wiring each in with ``<xi:include>`` in manifest order, so
the directory becomes a complete, compilable PreTeXt project. PreTeXt assembles
a document exactly this way — ``<xi:include>`` of the parts under a
``<book>``/``<article>`` root.

It is pure, deterministic string/XML building — no LLM, no I/O (see decision
#37: mechanical structure is assembled deterministically, AI is reserved for
where it adds genuine value). The service layer wraps this with the file reads
and writes.

Root element (decision #34, Option U)
-------------------------------------
``root_element`` is exposed as a parameter rather than hard-coded, because the
right root depends on the document and the author's intent — a choice a person
meets in the Output pane, not one the pipeline should make for everyone:

* ``"article"`` legally takes ``<section>`` children, so the ``<section>``
  fragments slot straight in with a bare ``<xi:include>``.
* ``"book"`` takes ``<chapter>`` children, *not* top-level ``<section>``. So a
  chapter fragment is wrapped in a generated ``<chapter>`` — ``book > chapter >
  section`` is valid PreTeXt. The wrapper carries the chapter's title from the
  manifest; the included ``<section>`` keeps its own, which is mild redundancy
  a human can collapse, and is the price of not rewriting the fragments here.
* ``"auto"`` (the default) picks ``book`` when the manifest contains any
  ``chapter``-typed entry (the textbook shape LyreTeXt is built for), else
  ``article``.

Front/back matter caveat
------------------------
Front- and back-matter entries are placed in ``<frontmatter>``/``<backmatter>``
— their structurally-intended home. Those wrappers have their own content
model, so a ``<section>``-rooted matter fragment may still need the author's
hand to validate; that is a property of the fragment's shape, which this
assembler does not rewrite, not of where it is placed.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Sequence
from xml.sax.saxutils import escape, quoteattr

_XINCLUDE_NS = "http://www.w3.org/2001/XInclude"

# Manifest entry types that are matter rather than body chapters.
_FRONT = "front_matter"
_BACK = "back_matter"


def resolve_root(manifest: Sequence[dict], root_element: str = "auto") -> str:
    """Resolve the root element to use, honouring an explicit choice.

    ``"book"``/``"article"`` are returned as given; anything else (``"auto"``
    or an unrecognised value) is decided from the manifest: ``book`` if it
    holds any ``chapter``-typed entry, else ``article``.
    """
    if root_element in ("book", "article"):
        return root_element
    has_chapter = any(entry.get("type") == "chapter" for entry in manifest)
    return "book" if has_chapter else "article"


def build_main_ptx(
    manifest: Sequence[dict],
    *,
    title: str | None = None,
    root_element: str = "auto",
) -> str:
    """Build the unifying ``main.ptx`` as a string.

    *manifest* is the run's ordered manifest: a list of dicts each with at
    least ``output_path`` and ``type`` (``"chapter"``/``"front_matter"``/
    ``"back_matter"``), and optionally ``name``. ``<xi:include>`` hrefs are the
    bare filenames, because ``main.ptx`` is written alongside the fragments in
    the output directory.
    """
    root = resolve_root(manifest, root_element)
    doc_title = title or "Untitled"
    root_id = _ncname(doc_title, fallback=root)

    fronts = [e for e in manifest if e.get("type") == _FRONT]
    backs = [e for e in manifest if e.get("type") == _BACK]
    chapters = [e for e in manifest if e.get("type") not in (_FRONT, _BACK)]

    lines: list[str] = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append("<!-- Generated by LyreTeXt. Unifying project manifest; edit by hand as needed. -->")
    lines.append(f'<pretext xmlns:xi="{_XINCLUDE_NS}">')
    lines.append(f'  <{root} xml:id="{root_id}">')
    lines.append(f"    <title>{escape(doc_title)}</title>")

    if fronts:
        lines.append("    <frontmatter>")
        for entry in fronts:
            lines.append(f"      <xi:include href={quoteattr(_href(entry))}/>")
        lines.append("    </frontmatter>")

    for entry in chapters:
        href = quoteattr(_href(entry))
        if root == "book":
            stem = Path(entry["output_path"]).stem
            chap_id = _ncname(stem, fallback="ch")
            chap_title = entry.get("name") or stem
            lines.append(f'    <chapter xml:id="{chap_id}">')
            lines.append(f"      <title>{escape(chap_title)}</title>")
            lines.append(f"      <xi:include href={href}/>")
            lines.append("    </chapter>")
        else:
            lines.append(f"    <xi:include href={href}/>")

    if backs:
        lines.append("    <backmatter>")
        for entry in backs:
            lines.append(f"      <xi:include href={quoteattr(_href(entry))}/>")
        lines.append("    </backmatter>")

    lines.append(f"  </{root}>")
    lines.append("</pretext>")
    return "\n".join(lines) + "\n"


def _href(entry: dict) -> str:
    """The ``<xi:include>`` href for a manifest entry: its bare filename."""
    return Path(entry["output_path"]).name


def _ncname(value: str, *, fallback: str) -> str:
    """Coerce *value* into a valid-enough XML NCName for an ``xml:id``.

    NCNames may not contain whitespace and must start with a letter or
    underscore. Non-conforming characters collapse to ``-``; if the result
    would not start legally, it is prefixed with *fallback*.
    """
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "-", (value or "").strip()).strip("-._")
    if not cleaned:
        return fallback
    if not re.match(r"[A-Za-z_]", cleaned):
        return f"{fallback}-{cleaned}"
    return cleaned


__all__ = ["build_main_ptx", "resolve_root"]
